### ISSUE TITLE
Add missing permission message to /b

### ISSUE THREAD

**Issue by StealWonders** [ervinnnc/VoxelSniper#11]
When using /b when not having permission it will just set the brush to nothing.
This was very confusing at first as I thought this was caused by some other plugin. In fact, it was just my permissions set up wrong. I believe it would be better if it would reply with a "You don't have permission to do this" message or similar.

**Comment by ghost** [comment]
Hey, thanks for your submission!

Could you provide extra details to this and steps to replicate? Thanks.

**Comment by StealWonders** [comment]
Well just don't give players the permission to use voxelsniper.brush.* ;)
