### ISSUE TITLE
Allow for changing of override blocks in OverlayBrush

### ISSUE THREAD

**Issue by StealWonders** [ervinnnc/VoxelSniper#8]
Currently, the OverlayBrush has a specific hardcoded list of Materials which can be replaced.
![firefox_eQW4w6aJHp](https://user-images.githubusercontent.com/6114858/78776889-d8f2c480-7998-11ea-88b8-937bed8071ca.png)
It would be really cool if you could just sneak and right-click a block (or multiple) to add them to this list of blocks to overlay.
Then you wouldn't have to use some weird worldedit commands to get the top most layer or two top most layers and replace it with the block you like.

**Comment by ghost** [comment]
Hey, thanks for your submission!

This is the intended behaviour as per original VoxelSniper developers. All Overlay brushes have two modes, which is to only replace "natural" materials, which are the ones listed in your screenshot above, and another mode which allows replacing of ALL materials. 

As the Overlay brushes were intended to do "topsoil filling", it by default only targets natural blocks.

It is a possibility that I could add VoxelList (an already coded feature) support for this brush, which will allow manual adding and removing of blocks.

Thanks!
